### ISSUE TITLE
runPipeline in Web Worker with Firefox

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itk-wasm#714]
Firefox gives an error when a Web Worker calls
```
    const { outputs } = await runPipeline(
      false,
      pipelinePath,
      taskArgs,
      desiredOutputs,
      inputs
    )
```
`Error: Dynamic module import is disabled or not supported in this context`

It there another way to run "pipelines" in workers?  

Or to workaround Firefox's dynamic imports in Web Workers: Modify runPipeline to accept a user created `PipelineEmscriptenModule` with a statically imported JS module?

**Comment by thewtex** [comment]
> Firefox's dynamic imports in Web Workers:

Yes, this is a practical limitation. More information:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/9dfa2b8a7086cef2fec04605073c24d2660bf6b0/src/core/createWebWorkerPromise.ts#L52-L54

> It there another way to run "pipelines" in workers?

Pass `null` instead of `false` to `runPipeline` from the main thread, and its runs in a Web Worker.

>  runPipeline to accept a user created PipelineEmscriptenModule

This was recently added:

- https://github.com/InsightSoftwareConsortium/itk-wasm/pull/709
- https://github.com/InsightSoftwareConsortium/itk-wasm/pull/711

**Comment by PaulHax** [comment]
`blob:http://...` is getting inserted by Webpack in a web worker's `__webpack_public_path__`

A few (unnecessary?) workarounds for Webpack bundled worker in itk-vtk-viewer:
https://github.com/Kitware/itk-vtk-viewer/pull/632/files#diff-78c2cbc750bff556e21821a651bf59e8126ce35c641510222aed538368a2ddebR16-R38

**Comment by thewtex** [comment]
@PaulHax I added a few comments inline that hopefully explain the lack of need for the workarounds.

**Comment by PaulHax** [comment]
Ending up adjusting the itkConfig in the pipeline calling web worker for our Webpack app:

https://github.com/Kitware/itk-vtk-viewer/blob/591b90ae4263c6adf8aeacd0a0dcef438d2ae711/src/IO/ResampleLabelImage/resampleLabelImage.js#L14-L30
